name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pytest-html

      - name: Ejecutar tests
        run: |
          PYTHONPATH=. pytest --html=report.html

      - name: Subir reporte
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: report.html
